name: 02-workflow-events
on:
  pull_request:
  schedule: 
    - cron: '*/15 * * * *'

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Event name step
        run: echo "Name of the event" ${{ github.event_name }}
