name: Workflow Expression
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        type: boolean
        default: false

jobs:
  conditional-data:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print start-up data'
        if: ${{ inputs.debug == true }}
        run: |
          echo "Triggered by: ${{ github.event_name}}"
          echo "Branch: ${{ github.ref }}"
      -  name: Print start-up data
         if: ${{ inputs.debug == true  && github.ref == 'refs/heads/main' }}
         run: echo "This job was triggered from the main branch"