name: Workflow with outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: Status of the build
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: |
          echo "GITHUB_OUTPUT is located at" $GITHUB_OUTPUT
      - name: Build
        id: build
        run: |
          echo "GITHUB_OUTPUT is located at" $GITHUB_OUTPUT
          echo "output1=value1" >> $GITHUB_OUTPUT
          echo "output2=value2" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying the build"